language: ruby

sudo: false

install:
  - gem install dep
  - dep install
  - def -f .gems.dev install

script: make test

deploy:
  provider: script
  script: curl -G https://redis.io/deploy --data-urlencode token=$DEPLOY_TOKEN
  on:
    branch: master
